export const Users = [
  {
    id: 1,
    profilePicture: "/profiles/ammaProfile.JPG",
    userName: "Kamalakshi",
  },
  {
    id: 2,
    profilePicture: "profiles/appa-profile.JPG",
    userName: "Mallayya",
  },
  {
    id: 3,
    profilePicture: "profiles/chinnappaProfile.JPG",
    userName: "Chinmay",
  },
  {
    id: 4,
    profilePicture: "profiles/donProfile.JPG",
    userName: "Guru",
  },
  {
    id: 5,
    profilePicture: "profiles/dummiProfile.JPG",
    userName: "Susmitha",
  },
  {
    id: 6,
    profilePicture: "profiles/madhu-profile.JPG",
    userName: "Madhu",
  },
  {
    id: 7,
    profilePicture: "profiles/sowmya-profile.JPG",
    userName: "Sowmya",
  },
  {
    id: 8,
    profilePicture: "profiles/maProfile.JPG",
    userName: "Pranitha",
  },
  {
    id: 9,
    profilePicture: "profiles/ayyappaProfile.JPG",
    userName: "Ayyappa",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "God bless All",
    photo: "/posts/ammaPost.JPG",
    date: "15 seconds ago",
    userId: 1,
    like: 125,
    comment: 33,
  },
  {
    id: 2,
    desc: "God bless",
    photo: "/posts/appa-post.JPG",
    date: "12 minutes ago",
    userId: 2,
    like: 25,
    comment: 3,
  },
  {
    id: 3,
    desc: "Rock",
    photo: "/posts/chinnappa-post.JPG",
    date: "5 minutes ago",
    userId: 3,
    like: 15,
    comment: 3,
  },

  {
    id: 4,
    desc: "Don",
    photo: "/posts/donPost.JPG",
    date: "1 minute ago",
    userId: 4,
    like: 5,
    comment: 3,
  },
  {
    id: 5,
    desc: "God bless All",
    photo: "/posts/dummiPost.JPG",
    date: "1 hour ago",
    userId: 5,
    like: 15,
    comment: 7,
  },
  {
    id: 6,
    desc: "Madhu",
    photo: "/posts/ammaPost2.JPG",
    date: "2 seconds ago",
    userId: 6,
    like: 1,
    comment: 1,
  },
  {
    id: 7,
    desc: "Hello",
    photo: "/posts/sowmya-post1.JPG",
    date: "15s ago",
    userId: 7,
    like: 125,
    comment: 33,
  },
  {
    id: 8,
    desc: "...",
    photo: "/posts/maPost.JPG",
    date: " 2 minutes ago",
    userId: 8,
    like: 57,
    comment: 57,
  },
  {
    id: 9,
    desc: "Keep it simple",
    photo: "/posts/ayyappa-post.JPG",
    date: "15s ago",
    userId: 9,
    like: 125,
    comment: 33,
  },
  {
    id: 10,
    desc: "Believe in number 1",
    photo: "/posts/ayyappa-post2.JPG",
    date: "15s ago",
    userId: 9,
    like: 125,
    comment: 33,
  },
  {
    id: 11,
    desc: "I am Sowmya",
    photo: "/posts/sowmya-post2.JPG",
    date: "15s ago",
    userId: 7,
    like: 125,
    comment: 33,
  },
];
